### ISSUE TITLE
RSA-SHA1 key blocked in GitHub

### ISSUE THREAD

**Issue by MqllR** [gohypergiant/terraform-kubernetes-flux2-bootstrap#7]
Hey!

Today, GitHub dropped the support to RSA-SHA1 keys: https://github.blog/2021-09-01-improving-git-protocol-security-github/

Unfortunately, the terraform resources [private_key](https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key) create this kind of keys.

I personally switched to ECDSA using the same terraform resources.

**Comment by bbriggs** [comment]
Hey @MqllR, thanks for opening this issue. I'll go ahead and triage this and get a fix out.
